spring.application.name=hospiosk-backend

spring.datasource.url=jdbc:mysql://localhost:3306/hospiosk_project
spring.datasource.username=root
spring.datasource.password=rahul2621
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

razorpay.key.id=rzp_test_SFFBZE3PmY7fBw
razorpay.key.secret=9irV1KSW7PtSRdvfxNyrIz3o
